module.exports = {
  extends: [
    '@nuxtjs',
    'eslint:recommended',
    'plugin:wdio/recommended',
    'plugin:vue/recommended',
    'plugin:security/recommended',
    'plugin:anti-trojan-source/recommended',
  ],
  plugins: ['wdio'],
  env: {
    browser: true,
    node: true,
    mocha: true,
  },
  rules: {
    'no-debugger': process.env.NODE_ENV === 'development' ? 'warn' : 'error',
    'comma-dangle': ['error', 'always-multiline'],
    'no-extra-semi': 'error',
    semi: ['error', 'always'],
    'space-before-function-paren': ['error', {
        anonymous: "never",
        named: "never",
        asyncArrow: "always"
      }
    ],
    camelcase: 'error',
    eqeqeq: ['error', 'always', { null: 'ignore' }],
    'one-var': ['error', 'never'],
    'no-eval': 'error',
    'no-useless-concat': 'error',
    'prefer-template': 'error',
    'grouped-accessor-pairs': ['error', 'getBeforeSet'],
    'no-else-return': ['error', { allowElseIf: false }],
    'no-multiple-empty-lines': [2, { max: 2, maxEOF: 1 }],
    'newline-per-chained-call': ['error', { ignoreChainWithDepth: 2 }],
    'no-sequences': ['error', { allowInParentheses: false }],
    'padding-line-between-statements': ['error',
      { blankLine: 'always', prev: '*', next: 'return' },
      { blankLine: 'always', prev: 'const', next: '*' },
      { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
      { blankLine: 'any', prev: ['const', 'let', 'var'], next: ['const', 'let', 'var'] },
      { blankLine: 'always', prev: ['block', 'multiline-block-like', 'for', 'if', 'multiline-expression'], next: '*' },
    ],
    'brace-style': 'error',
    'object-curly-newline': ['error', { consistent: true }],
    'array-bracket-newline': ['error', 'consistent'],
    'array-element-newline': ['error', 'consistent'],
    'multiline-ternary': ['error', 'always-multiline'],
    'no-nested-ternary': 'error',
    'object-shorthand': ['error', 'properties'],
    'arrow-body-style': ['error', 'as-needed'],
    'max-statements-per-line': 'error',
    'import/no-dynamic-require': 'error',

    // vue
    'vue/multi-word-component-names': 0,
    'vue/html-indent': ['error', 2],
    'vue/script-indent': ['error', 2, {
      baseIndent: 0,
      switchCase: 1,
    }],
    'vue/html-quotes': ['error', 'double', { avoidEscape: false }],
    'vue/attribute-hyphenation': ['error', 'never'],
    'vue/object-curly-spacing': ['error', 'always'],
    'vue/attributes-order': 'error',
    'vue/order-in-components': 'error',
    'vue/new-line-between-multi-line-property': 'error',
    'vue/v-on-event-hyphenation': 'error',
    'vue/custom-event-name-casing': 'error',
    'vue/no-unused-refs': 'error',
    'vue/no-use-v-if-with-v-for': 'error',
    'vue/no-reserved-keys': 'error',
    'vue/no-mutating-props': 'error',
    'vue/this-in-template': 'error',
    'vue/padding-line-between-blocks': 'error',
    'vue/component-name-in-template-casing': ['error', 'PascalCase'],
    'vue/html-closing-bracket-newline': ['error', {
      singleline: 'never',
      multiline: 'always',
    }],
    'vue/html-closing-bracket-spacing': ['error', {
      startTag: 'never',
      endTag: 'never',
      selfClosingTag: 'always',
    }],
    'vue/no-potential-component-option-typo': ['error', {
      presets: ['all'],
    }],
    'vue/multiline-html-element-content-newline': ['error', {
      ignoreWhenEmpty: true,
      allowEmptyLines: false,
    }],
    'vue/no-unused-properties': ['error', {
      groups: [
        'props',
        'data',
        'computed',
        'methods',
      ],
      ignorePublicMembers: true,
    }],
  },
};
