module.exports = {
  arrowParens: 'avoid',
  bracketSpacing: true,
  htmlWhitespaceSensitivity: 'css',
  vueIndentScriptAndStyle: false,
  insertPragma: false,
  jsxBracketSameLine: false,
  jsxSingleQuote: false,
  disableLanguages: [],
  printWidth: 90,
  proseWrap: 'preserve',
  requirePragma: false,
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
}
